### ISSUE TITLE
Install Dependencies error

### ISSUE THREAD

**Issue by tuanpeto** [giongto35/cloud-game#242] opened 2020-10-30 07:41 UTC
I follow the Install Dependencies and try to run Script make dev.run i get there error can u help me?

# github.com/giongto35/cloud-game/v2/pkg/util
exec: "gcc": executable file not found in $PATH
# github.com/go-gl/gl/v4.1-core/gl
exec: "gcc": executable file not found in $PATH
# github.com/veandco/go-sdl2/sdl
exec: "gcc": executable file not found in $PATH
# github.com/gen2brain/x264-go/x264c
exec: "gcc": executable file not found in $PATH
# gopkg.in/hraban/opus.v2
exec: "gcc": executable file not found in $PATH

**Comment by sergystepanov** [comment] 2020-10-30 10:06
It seems that the readme file is a bit outdated, could you try to install GCC (C language compiler):
```
sudo apt-get update
sudo apt-get install -y gcc 
```

**Comment by tuanpeto** [comment] 2020-10-30 15:59
> It seems that the readme file is a little bit incomplete, may I ask you to try to install GCC (C language compiler):
> 
> ```
> sudo apt-get update
> sudo apt-get install -y gcc 
> ```

Thanks for your help, but I also got this error after running gcc install

root@ubutun:~# make dev.run
go build -o bin/coordinator ./cmd/coordinator
go: finding github.com/giongto35/cloud-game/pkg/coordinator latest
go: finding github.com/giongto35/cloud-game/pkg/util/logging latest
go: finding github.com/giongto35/cloud-game/pkg latest
go: finding github.com/giongto35/cloud-game/pkg/util latest
build github.com/giongto35/cloud-game/v2/cmd/coordinator: cannot find module for path github.com/giongto35/cloud-game/pkg/coordinator

**Comment by sergystepanov** [comment] 2020-10-30 16:33
@tuanpeto, that's rather strange. You are using Golang version 13 or higher, is it right (`go version`)?
I advise you to clone the latest version of the app or update it and clear all the cache:
```
git pull
go clean -modcache
make dev.run
```

**Comment by tuanpeto** [comment] 2020-10-31 08:46
> @tuanpeto, that's rather strange. You are using Golang version 13 or higher, is it right (`go version`)?
> I advise you to clone the latest version of the app or update it and clear all the cache:
> 
> ```
> git pull
> go clean -cache -modcache
> make dev.run
> ```
Thank you very much for your help! I have it installed but when I upload the game list and click on start game. Then the terminal error message as follows:

I1031 08:41:34.696074    1400 coordinator.go:59] Received a request to createOffer from browser via coordinator
I1031 08:41:34.696635    1400 webrtc.go:120] === StartClient ===
I1031 08:41:34.713475    1400 webrtc.go:140] Add video track
I1031 08:41:34.714075    1400 webrtc.go:230] Created Offer
I1031 08:41:34.714713    1400 coordinator.go:91] Start peerconnection 2aa0ff5e-0ab6-4808-94d5-433f791df910
I1031 08:41:34.715425    1400 webrtc.go:191] OnIceCandidate: candidate:foundation 1 udp 2130706431 45.77.171.205 40005 typ host
I1031 08:41:34.715970    1400 webrtc.go:191] OnIceCandidate: candidate:foundation 1 udp 1694498815 45.77.171.205 45014 typ srflx raddr 0.0.0.0 rport 45014
I1031 08:41:34.777485    1400 coordinator.go:108] Received answer SDP from browser
I1031 08:41:34.778100    1400 webrtc.go:263] Set Remote Description
I1031 08:41:34.778534    1400 webrtc.go:175] ICE Connection State has changed: checking
I1031 08:41:34.786070    1400 coordinator.go:129] Received remote Ice Candidate from browser
I1031 08:41:34.786264    1400 webrtc.go:274] Decoded Ice: candidate:4033732497 1 udp 2113937151 d7912ab5-c6c3-4f1e-ac75-a61124fd525c.local 65383 typ host generation 0 ufrag 9+PU network-cost 999
I1031 08:41:34.786404    1400 webrtc.go:282] Add Ice Candidate: candidate:4033732497 1 udp 2113937151 d7912ab5-c6c3-4f1e-ac75-a61124fd525c.local 65383 typ host generation 0 ufrag 9+PU network-cost 999
I1031 08:41:35.872963    1400 webrtc.go:175] ICE Connection State has changed: connected
I1031 08:41:35.874162    1400 webrtc.go:179] ConnectionStateConnected
I1031 08:41:35.874284    1400 webrtc.go:314] Start streaming
I1031 08:41:36.046197    1400 webrtc.go:159] Data channel 'game-input'-'824638230844' open.
I1031 08:41:41.038941    1400 coordinator.go:152] Received a start request from coordinator
I1031 08:41:41.039304    1400 coordinator.go:322] Loading game: Super Mario Bros
I1031 08:41:41.039445    1400 coordinator.go:328] Got Room from local  <nil>  ID:
I1031 08:41:41.039697    1400 room.go:135] Init new room:  6085744f91fc4573___Super Mario Bros { Super Mario Bros nes /root/cloud-game/assets/games/Super Mario Bros.nes}
I1031 08:41:41.039849    1400 room.go:280] Updated player Index to:  0
I1031 08:41:41.039980    1400 coordinator.go:346] Is PC in room false
I1031 08:41:41.040073    1400 handlers.go:126] Detach peerconnection
I1031 08:41:41.040556    1400 room.go:291] Start WebRTC session
I1031 08:41:41.040763    1400 room.go:157] Check  /root/.cr/save/6085744f91fc4573___Super Mario Bros.dat  on online storage :  false
I1031 08:41:41.040915    1400 room.go:428] Check if game is on cloud storage
I1031 08:41:41.041039    1400 room.go:159] Warn: Room 6085744f91fc4573___Super Mario Bros is not in online storage, error cloud storage was not initialized
I1031 08:41:41.041205    1400 room.go:163] Room 6085744f91fc4573___Super Mario Bros started. GameName: Super Mario Bros, WithGame: false
Libretro API version: 1
ROM size: 40976
  library_name: Nestopia
  library_version: 1.50-WIP a8e268b
  valid_extensions: nes|fds|unf|unif
  need_fullpath: false
  block_extract: false
[Log]: Custom palette path: ./pkg/emulator/libretro/system/custom.pal
[Log]: custom.pal not found in system directory.
[Log]: NstDatabase.xml path: ./pkg/emulator/libretro/system/NstDatabase.xml
[Log]: NstDatabase.xml required to detect region and some mappers.
panic: can't call pointer on a non-pointer Value

goroutine 103 [running]:
reflect.Value.pointer(...)
        /usr/local/go/src/reflect/value.go:95
reflect.Value.Pointer(0xfc0be0, 0xc0004748d0, 0xb6, 0x0)
        /usr/local/go/src/reflect/value.go:1456 +0x1b6
fmt.(*pp).fmtPointer(0xc000093040, 0xfc0be0, 0xc0004748d0, 0xb6, 0xc000000076)
        /usr/local/go/src/fmt/print.go:506 +0x65
fmt.(*pp).printValue(0xc000093040, 0xfc0be0, 0xc0004748d0, 0xb6, 0x76, 0x1)
        /usr/local/go/src/fmt/print.go:886 +0xc32
fmt.(*pp).printValue(0xc000093040, 0xfa5360, 0xc0004748a0, 0x99, 0xc000000076, 0x0)
        /usr/local/go/src/fmt/print.go:810 +0x1a68
fmt.(*pp).printArg(0xc000093040, 0xfa5360, 0xc0004748a0, 0xc000000076)
        /usr/local/go/src/fmt/print.go:716 +0x2b4
fmt.(*pp).doPrintf(0xc000093040, 0xfe62bb, 0x1c, 0xc0000e7528, 0x5, 0x5)
        /usr/local/go/src/fmt/print.go:1030 +0x168
fmt.Fprintf(0x10d94e0, 0xc000010020, 0xfe62bb, 0x1c, 0xc0000e7528, 0x5, 0x5, 0x1013358, 0xc0000e7578, 0x4e5a37)
        /usr/local/go/src/fmt/print.go:204 +0x72
fmt.Printf(...)
        /usr/local/go/src/fmt/print.go:213
github.com/giongto35/cloud-game/v2/pkg/emulator/libretro/nanoarch.videoSetPixelFormat(0xc000000001, 0xc00000ba00)
        /root/cloud-game/pkg/emulator/libretro/nanoarch/nanoarch.go:802 +0x197
github.com/giongto35/cloud-game/v2/pkg/emulator/libretro/nanoarch.coreEnvironment(0x7fdb0000000a, 0x7fdbbe7bf284, 0x10)
        /root/cloud-game/pkg/emulator/libretro/nanoarch/nanoarch.go:299 +0x66e
github.com/giongto35/cloud-game/v2/pkg/emulator/libretro/nanoarch._cgoexpwrap_73f2e66f7bd5_coreEnvironment(0x7fdb0000000a, 0x7fdbbe7bf284, 0x7fdba80023d0)
        _cgo_gotypes.go:737 +0x33
github.com/giongto35/cloud-game/v2/pkg/emulator/libretro/nanoarch._Cfunc_bridge_retro_load_game(0x7fdbbdd6be90, 0xc00047c0e0, 0xe39b00)
        _cgo_gotypes.go:378 +0x4a
github.com/giongto35/cloud-game/v2/pkg/emulator/libretro/nanoarch.coreLoadGame.func4(0xc00047c0e0, 0xc0004499e0)
        /root/cloud-game/pkg/emulator/libretro/nanoarch/nanoarch.go:633 +0x94
github.com/giongto35/cloud-game/v2/pkg/emulator/libretro/nanoarch.coreLoadGame(0xc00045c680, 0x32)
        /root/cloud-game/pkg/emulator/libretro/nanoarch/nanoarch.go:633 +0x593
github.com/giongto35/cloud-game/v2/pkg/emulator/libretro/nanoarch.(*naEmulator).LoadMeta(0xc00036c9a0, 0xc00045c680, 0x32, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/cloud-game/pkg/emulator/libretro/nanoarch/naemulator.go:193 +0xbc
github.com/giongto35/cloud-game/v2/pkg/worker/room.NewRoom.func1(0xc0003c0dc0, 0x2260, 0x7ffdff4e47a1, 0xe, 0x2328, 0x1, 0x0, 0x140, 0xf0, 0xfcab88, ...)
        /root/cloud-game/pkg/worker/room/room.go:183 +0x463
created by github.com/giongto35/cloud-game/v2/pkg/worker/room.NewRoom
        /root/cloud-game/pkg/worker/room/room.go:154 +0x3c8
Makefile:76: recipe for target 'dev.run' failed
make: *** [dev.run] Error 2

**Comment by sergystepanov** [comment] 2020-10-31 11:51
@tuanpeto, it's getting interesting (: I'm not quite sure what can lead to such errors. @giongto35, maybe you have any ideas?
In any case, @tuanpeto, you could try to remove [this](https://github.com/giongto35/cloud-game/blob/a42aebec886f479be43ad33661c43077085b1c6b/pkg/emulator/libretro/nanoarch/nanoarch.go#L802) line from the file and re-run `make dev.run` without it. I believe it should help in resolving your issue but I'm not sure about the rest of the app.
Apart from that, would you mind to show the output of each of these commands:
```
go version
```
```
go env
```
```
gcc -v
```
```
printenv
```
```
uname -a
```

**Comment by sergystepanov** [comment] 2020-10-31 12:35
Right. I reproduced it with Go 1.15.3. That's a bug in the Go. @tuanpeto, the previous version 1.15.2 and below should work. This bug is expected to be fixed in 1.15.4.

![image](https://user-images.githubusercontent.com/846874/97779311-40b76980-1b8e-11eb-8f0e-4f01ba4ad2f6.png)

**Comment by tuanpeto** [comment] 2020-11-01 09:37
> Right. I reproduced it with Go 1.15.3. That's a bug in Go itself. @tuanpeto, the previous version 1.15.2 and below should work. This bug is expected to be fixed in 1.15.4.
> Actually, it works in 1.15.3 without that line, so you could wait until my fix is merged into the master branch here then update your source code, or roll-back Go version.
> 
> ![image](https://user-images.githubusercontent.com/846874/97779311-40b76980-1b8e-11eb-8f0e-4f01ba4ad2f6.png)

Many thanks for your help. I did it with the lower Golang version, so sorry to you for my unprofessional questions.

**Comment by sergystepanov** [comment] 2020-11-01 09:49
Let's not exaggerate the matters of concern. Feel free to ask any questions / close this issue.

**Comment by giongto35** [comment] 2020-11-01 16:51
@sergystepanov the stable version of go is still 1.13 right :/ 
If Go version is up, maybe we have to comeback and look

**Comment by sergystepanov** [comment] 2020-11-01 18:36
@giongto35, 

> @sergystepanov the stable version of go is still 1.13 right :/
> If Go version is up, maybe we have to comeback and look

@giongto35, not exactly sure what you mean, the latest stable version is [1.15.3](https://golang.org/dl/).
And I tested a fix (my PR) on the bugged Go version and it seems to be working.

**Closed** 2020-11-08 16:07 UTC
